# Generated by Django 2.2.4 on 2020-12-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='21-212421_transparent-clothing-icon-png.png', upload_to='image'),
        ),
    ]
