# Generated by Django 2.2.4 on 2020-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0004_auto_20201224_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='21-212421_transparent-clothing-icon-png.png', upload_to='image'),
        ),
    ]
