# Generated by Django 2.2.4 on 2020-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0005_auto_20201224_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
