# Generated by Django 2.2.4 on 2020-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0006_auto_20201224_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/image'),
        ),
    ]
