# Generated by Django 2.2.4 on 2020-12-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0009_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
    ]
