# Generated by Django 2.2.4 on 2020-12-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(related_name='product', to='hollylandApp.Product'),
        ),
    ]
