# Generated by Django 2.2.4 on 2020-12-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0013_auto_20201225_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='hollylandApp.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(related_name='product_id', to='hollylandApp.Product'),
        ),
    ]
