# Generated by Django 2.2.4 on 2020-12-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0015_auto_20201225_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='hollylandApp.Product'),
        ),
    ]
