# Generated by Django 2.2.4 on 2020-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0016_auto_20201226_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
