# Generated by Django 2.2.4 on 2020-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0018_auto_20201226_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.FloatField(default=0),
        ),
    ]
