# Generated by Django 2.2.4 on 2020-12-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollylandApp', '0019_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
